ENG-7859: Support self-signed certificate provisioning at template level
cyralinc/terraform-cyral-sidecar-aws pull request #27
Opened 2022-03-07 15:51 UTC by Yowgf

[ENG-7859](https://cyralinc.atlassian.net/browse/ENG-7859): Support self-signed certificate provisioning at template level.

2022-03-08 19:14 UTC, Yowgf commented on README.md
> +| <a name="provider_aws"></a> [aws](#provider\_aws) | 4.4.0 |
I am not sure why, but terraform-docs made this change automatically. Is this right @VictorGFM   @wcmjunior ?

2022-03-09 13:48 UTC, ha2398 approved these changes
LGTM (but it's probably a good idea to wait for a more thorough review by the other reviewers)

2022-03-09 23:32 UTC, VictorGFM requested changes
The terraform code looks good! I just would like a little bit of context here, please correct me if I'm wrong, but I believe we still need to merge [this PR](https://github.com/cyralinc/sidecar-certificate-selfsigned/pull/1) for these changes in the sidecar module to work, right?

2022-03-09 23:32 UTC, VictorGFM commented on README.md
> +| <a name="provider_aws"></a> [aws](#provider\_aws) | 4.4.0 |
The AWS Provider version being bumped to version `4.4.0`, is an expected behavior in this case since the sidecar module uses the `>=` [version constraint](https://www.terraform.io/language/expressions/version-constraints#-2), which allows terraform to bump provider versions that are higher or equal to the value provided (without additional restriction). To avoid bumping to a major version, that may break the sidecar module, we can just pin the AWS version to the latest `3.x.x` version. Like:
```terraform
terraform {
  required_version = ">= 0.12"
  required_providers {
    aws = {
      version =  "3.74.3"
      source  = "hashicorp/aws"
    }
  }
}
```

2022-03-09 23:32 UTC, VictorGFM commented on versions.tf
>        version = ">= 3.22.0"
```suggestion
      version = "3.74.3"
```

2022-04-07 06:55 UTC, wcmjunior commented on README.md
> +| <a name="provider_aws"></a> [aws](#provider\_aws) | 4.4.0 |
Just a little more context here: in the past we had some issue with a missing feature in some older versions of the AWS Provider (`<3.22`) that caused the sidecar deployment to break in some customers using older AWS providers. We then realized we had to bump the minimum required version. At that time, we already had several releases past `3.22`, but `3.22` was the release that the actual feature was released and we decided to pin it. In this sense, please keep the minimum release pinned at `3.22` as it was before. If you need more information, please refer to the internal ticket `ENG-4998`.

2022-04-20 17:47 UTC, VictorGFM approved these changes
@Yowgf the overall code looks good, but please consider my comment below before merging the PR, thanks.

2022-04-20 17:47 UTC, VictorGFM commented on lambda_resources.tf
> +      SIDECAR_SELFSIGNED_CERTIFICATE_SIDECAR_HOSTS = local.self_signed_certificate_sidecar_hosts
Since the service name is [sidecar-certificate-selfsigned](https://github.com/cyralinc/sidecar-certificate-selfsigned/blob/main/internal/config/config.go#L21), shouldn't these env vars have the following prefix instead?
```suggestion
      SIDECAR_CERTIFICATE_SELFSIGNED_AWS_REGION    = data.aws_arn.cw_lg.region
      SIDECAR_CERTIFICATE_SELFSIGNED_SIDECAR_ID    = var.sidecar_id
      SIDECAR_CERTIFICATE_SELFSIGNED_SIDECAR_HOSTS = local.self_signed_certificate_sidecar_hosts
```

2022-04-21 00:21 UTC, Yowgf commented on lambda_resources.tf
> +      SIDECAR_SELFSIGNED_CERTIFICATE_SIDECAR_HOSTS = local.self_signed_certificate_sidecar_hosts
Thanks Victor!

2022-04-22 05:00 UTC, merged