ENG-8228: Add use_inbound_port_range variable to avoid cartesian product in security group rules
cyralinc/terraform-cyral-sidecar-aws pull request #28
Opened 2022-04-01 19:16 UTC by VictorGFM

See [ENG-8228](https://cyralinc.atlassian.net/browse/ENG-8228): Create sidecar template feature to avoid cartesian product in security group rules.

2022-04-04 22:59 UTC, wcmjunior requested changes
See comments.

2022-04-04 22:59 UTC, wcmjunior commented on ec2_resources.tf
> +  # If use_inbound_port_range is true, it will create DB Inbound Rules per CIDR using
```suggestion
  # If reduce_security_group_rules_count is true, it will create DB Inbound Rules per CIDR using
```

2022-04-05 13:05 UTC, VictorGFM commented on README.md
> +    version = "2.6.4" # terraform module version
Oh, I didn't notice that, thanks for pointing that out

2022-04-05 20:20 UTC, wcmjunior approved these changes

2022-04-05 20:20 UTC, merged